version: '3'

services:
  redis:
    image: redis
    restart: always
    container_name: 'app_redis'
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    restart: always
    container_name: 'app_flask'
    command: python manage.py runserver
    volumes:
      - .:/code
    ports:
      - '8000:8000'
  celery:
    build: .
    container_name: 'app_celery'
    command: celery -A app.celery worker -B
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis