CREATE TABLE group_food
(
  id integer NOT NULL,
  description text NOT NULL,
  CONSTRAINT pk_group_food PRIMARY KEY (id)
);

CREATE TABLE food
(
  id integer NOT NULL,
  food_group_id integer NOT NULL,
  description text NOT NULL,
  CONSTRAINT pk_food PRIMARY KEY (id),
  CONSTRAINT fk_group_food
      FOREIGN KEY(food_group_id)
	  REFERENCES group_food(id)
);

CREATE TABLE nutritions
(
  id integer NOT NULL,
  unit character varying(50) NOT NULL,
  tag character varying(50) NOT NULL,
  name text NOT NULL,
  CONSTRAINT pk_nutritions PRIMARY KEY (id)
);

CREATE TABLE food_nutrients
(
  id integer GENERATED BY DEFAULT AS IDENTITY,
  nutrition_value real NOT NULL,
  food_id integer NOT NULL,
  nutrition_id integer NOT NULL,
  CONSTRAINT pk_food_nutrients PRIMARY KEY (id),
  CONSTRAINT fk_food_nutrient FOREIGN KEY (nutrition_id)
      REFERENCES nutritions (id) MATCH SIMPLE,
  CONSTRAINT fk_nutrient_food FOREIGN KEY (food_id)
      REFERENCES food (id) MATCH SIMPLE
);

CREATE TABLE norms
(
  id integer GENERATED BY DEFAULT AS IDENTITY,
  sex boolean NOT NULL,
  min_age integer NOT NULL,
  max_age integer NOT NULL,
  nutrition_id integer NOT NULL,
  norm_value real NOT NULL,
  unit character varying(50) NOT NULL,
  active boolean,
  CONSTRAINT norms_pkey PRIMARY KEY (id),
  CONSTRAINT fk_norms_nutrition FOREIGN KEY (nutrition_id)
      REFERENCES nutritions (id) MATCH SIMPLE
);

CREATE TABLE users
(
 id            integer GENERATED BY DEFAULT AS IDENTITY,
 firstname        text NOT NULL,
 lastname         text NOT NULL,
 sex              boolean NOT NULL,
 birthday         date NOT NULL,
 email            text NOT NULL,
 telegram_account text NOT NULL,
 CONSTRAINT PK_users PRIMARY KEY ( id )
);

CREATE TABLE menu_week
(
 id            integer GENERATED BY DEFAULT AS IDENTITY,
 user_id       integer NOT NULL,
 food_id       integer NOT NULL,
 netto         integer NOT NULL,
 creation_date date NOT NULL,
 CONSTRAINT PK_menu_week PRIMARY KEY ( id ),
 CONSTRAINT FK_83 FOREIGN KEY ( user_id ) REFERENCES users ( id ),
 CONSTRAINT FK_86 FOREIGN KEY ( food_id ) REFERENCES food ( id )
);

