CREATE TABLE users
(
 id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 firstname        text NOT NULL,
 lastname         text NOT NULL,
 sex              boolean NOT NULL,
 birthday         date NOT NULL,
 email            text NOT NULL,
 telegram_account text NOT NULL,
 CONSTRAINT PK_users PRIMARY KEY ( id )
);

CREATE TABLE menu_week
(
 id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id       integer NOT NULL,
 food_id       integer NOT NULL,
 netto         integer NOT NULL,
 creation_date date NOT NULL,
 CONSTRAINT PK_menu_week PRIMARY KEY ( id ),
 CONSTRAINT FK_83 FOREIGN KEY ( user_id ) REFERENCES users ( "id" ),
 CONSTRAINT FK_86 FOREIGN KEY ( food_id ) REFERENCES food ( "id" )
);

CREATE INDEX fkIdx_84 ON menu_week
(
 user_id
);

CREATE INDEX fkIdx_87 ON menu_week
(
 food_id
);

